### ISSUE TITLE
Core files aren't written by OpenJDK on macOS Catalina

### ISSUE THREAD

**Issue by chipkillmar** [AdoptOpenJDK/openjdk-support#98]
* **Platform and architecture (e.g. Linux/x64**:
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E287
```

I can't replicate this on High Sierra.

* **Java version (from "java --version") e.g. 1.8.0_181, 11.0.4+11 etc.**:

`11.0.7+10`

* **Variant e.g. HotSpot or OpenJ9**:

HotSpot

* **Have you tested it with other vendors' java**:

No.

* **Steps to reproduce**:

1.  Clone OpenJDK `jdk11u` GitHub mirror:

```
$ git clone https://github.com/openjdk/jdk11u.git && cd jdk11u
```

2. configure:

```
$ bash ./configure --with-target-bits=64 --with-debug-level=fastdebug --disable-warnings-as-errors --with-native-debug-symbols=internal
```

3. make:

```
$ make all
```

4. Set core file size to `unlimited`:

```
$ ulimit -c unlimited
```

5. Test `/cores` directory exists and is writable:

```
$ touch /cores/test && rm /cores/test
```

6. Attempt to generate a core dump:

```
$ ./build/macosx-x86_64-normal-server-fastdebug/jdk/bin/java -XX:ErrorHandlerTest=13
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000000000000f, pid=58404, tid=8451
#
# JRE version: OpenJDK Runtime Environment (11.0.8) (fastdebug build 11.0.8-internal+0-adhoc.chipkillmar.jdk11u)
# Java VM: OpenJDK 64-Bit Server VM (fastdebug 11.0.8-internal+0-adhoc.chipkillmar.jdk11u, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# C  0x000000000000000f
#
# Core dump will be written. Default location: /cores/core.58404
#
# An error report file with more information is saved as:
# /private/tmp/jdk11u/hs_err_pid58404.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
Current thread is 8451
Dumping core ...
Abort trap: 6
```

7. Even though the above error report indicates a core file was written, the `/cores` directory is empty:

```
$ ls -a /cores
.  ..
```

* **Error messsage and/or description of what is not working as expected**:

The core dump `/cores/core.58404` should have been written.

**Comment by karianna** [comment]
Hmm, this is a nightly build, can you check with 11.0.7?

**Comment by chipkillmar** [comment]
@karianna I'm seeing this with the latest `11.0.7+10` macOS build.  I used the latest sources from the `jdk11u` GitHub mirror to provide instructions for replicating the issue.

**Comment by karianna** [comment]
@chipkillmar I suspect with is Mac OS X's file protection going on.  What are the permissions on that folder?

**Comment by chipkillmar** [comment]
@karianna the directory is world writable.  Step 5 above creates a `test` file in `/cores` to confirm this.

```
$ ls -la / | grep cores
drwxrwxrwt    2 root  wheel    64 May  4 10:08 cores
```

FWIW, I can't replicate this on High Sierra.

**Comment by smlambert** [comment]
Potentially related: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1282

**Comment by chipkillmar** [comment]
@smlambert I'm fairly sure this isn't related to directory permissions.  The `/cores` directory is world writable, and I can create a `test` file in it using `touch`.

**Comment by smlambert** [comment]
Yes @chipkillmar , saw your comment after I posted mine.  Cheers!

**Comment by karianna** [comment]
Hi @chipkillmar - thanks for the extra info I'll try to replicate locally (I'm still a little suspicious that Mac OS X might be blocking the JVM (which is an unnotarized binary) from writing, whereas you manually can - but let's see :-).

**Comment by karianna** [comment]
OK, I've tested locally.  You need to ensure that the _/cores_ directory has the user:group +w permissions set so that the user:group of the JVM (which is probably `<your username>:staff` has sufficient write permission to the _/cores_ directory (which is probably `root:admin`).  Omnce I fixed that locally it worked for me.

**Comment by chipkillmar** [comment]
@karianna thanks for looking into this.  _I still can't get this to work on Catalina_; previous macOS versions work fine.

On Catalina, I'm seeing `Abort trap: 6`, but no core file is created.

On previous macOS versions, I'm seeing `Abort trap: 6 (core dumped)`, and the core file is successfully created.

**Comment by karianna** [comment]
> @karianna thanks for looking into this. _I still can't get this to work on Catalina_; previous macOS versions work fine.
> 
> On Catalina, I'm seeing `Abort trap: 6`, but no core file is created.
> 
> On previous macOS versions, I'm seeing `Abort trap: 6 (core dumped)`, and the core file is successfully created.

Hmm, I'm on 10.15.4 (Catalina).  Can you send the `ls -la` output for the `/cores` and the directory that the java is in again?  I see that there's a `t` on the end of you /cores which I don't have...

**Comment by chipkillmar** [comment]
@karianna I still don't believe it's a directory permission issue.  Initially, I can see the core dump as a result of running `java -XX:ErrorHandlerTest=13`.

However, after cloning and running the following Spring Boot demo app, I can no longer get the JVM to produce a core dump.  Perhaps this has something to do with the application firewall on Catalina?

```
# Basic Spring Boot 2 demo app.
$ git clone https://github.com/chipkillmar/demo.git && cd demo

# Set JAVA_HOME to the OpenJDK 11u debug build created above.
$ JAVA_HOME=/tmp/jdk11u/build/macosx-x86_64-normal-server-fastdebug/jdk ./gradlew bootRun

# Core file isn't created, even though the JVM indicates it should be written.
$ /tmp/jdk11u/build/macosx-x86_64-normal-server-fastdebug/jdk/bin/java -XX:ErrorHandlerTest=13
```

**Comment by karianna** [comment]
> @karianna I still don't believe it's a directory permission issue. Initially, I can see the core dump as a result of running `java -XX:ErrorHandlerTest=13`.
> 
> However, after cloning and running the following Spring Boot demo app, I can no longer get the JVM to produce a core dump. Perhaps this has something to do with the application firewall on Catalina?
> 
> ```
> # Basic Spring Boot 2 demo app.
> $ git clone https://github.com/chipkillmar/demo.git && cd demo
> 
> # Set JAVA_HOME to the OpenJDK 11u debug build created above.
> $ JAVA_HOME=/tmp/jdk11u/build/macosx-x86_64-normal-server-fastdebug/jdk ./gradlew bootRun
> 
> # Core file isn't created, even though the JVM indicates it should be written.
> $ /tmp/jdk11u/build/macosx-x86_64-normal-server-fastdebug/jdk/bin/java -XX:ErrorHandlerTest=13
> ```

I'm really not sure at this stage.  I have the firewall on and seem to have the same Mac OS X version as you :-/

**Comment by chipkillmar** [comment]
@karianna Thanks, I'm going to close this because this issue appears to be isolated to my development environment.

**Comment by karianna** [comment]
> @karianna Thanks, I'm going to close this because this issue appears to be isolated to my development environment.

So sorry we weren't able to help further!

**Comment by andrew-m-leonard** [comment]
@chipkillmar this is a known issue on Catalina at least with how openj9 produce the system dumps, see: https://github.com/AdoptOpenJDK/openjdk-build/issues/1778
